### ISSUE TITLE
Too many disks = no graph

### ISSUE THREAD

**Issue by luizlinux** [nmonvisualizer/nmonvisualizer#21]
When analyzing servers with a lot of disks the diskbusy graph area gets all filled up with the disk names and shows no graphic. Splitting the disks into separate graphs like diskbusy1, diskbusy3, etc, was a nice idea, but the amount of disks seem to be too high.

Maybe, I don't know if its possible, adding a scrollbar on the side so we can scroll up and down from the names and graph areas would prevent this behavior.

![2015-05-27_16-40-37](https://cloud.githubusercontent.com/assets/10618435/7845737/326123a6-048f-11e5-9919-fc112841d7b9.png)

thanks

**Comment by hpresnall** [comment]
This seems to be an issue with JFreeChart - there is no option to truncate the legend. The only solution I have found it to make the chart bigger. Obviously this is limited to your resolution in the GUI. You can set the size in a custom report but I am not sure you could make it big enough to show hundreds of disks.

A custom report may be the best option. With that you could just select the disks you want via multiple `<field>` elements.

**Comment by luizlinux** [comment]
Thanks for the reply Hunter.

Perhaps you could reduce the amount of disks per single report and split them into separate reports, like diskbusy1, diskbusy2 etc..

**Comment by hpresnall** [comment]
It may be possible to do this but it would require a lot more preprocessing since the charting engine doesn't have generic 'splitting' kind of filter on it. I would have to do it manually (ie one chart xml for disks 0-24, one for disks 25-50, etc). Not sure if that helps or not.

It may be easier to use the disk grouping feature of NMON and filter out the data at collection time.
