### ISSUE TITLE
360 NMON files

### ISSUE THREAD

**Issue by Neysser** [nmonvisualizer/nmonvisualizer#32]
Hi,

Firstly, thanks for this great app. I have 365 nmon files of a server and I would like to see only CPU comsuption in only one graph (or file csv) through this year, but it will impossible because i dont have enough memory to parse all files.
So, how can I parse only CPU data instead of NMONs files ? by command line ?

Thanks,

**Comment by hpresnall** [comment]
I am pretty sure this wouldn't work on the command line either since most of the memory is used holding the NMON data, not for the GUI.

Can you confirm that there aren't any messages being logged like `not overwriting existing XXX data`? If there are, you can save some memory by opening the log (`CTRL-L`) and setting the level to `SEVERE`. This prevents those messages and limits the memory used by the text field in that window that remains allocated even if you clear the logs.

You can also try running with more memory. Make sure you are using a 64 bit JVM and you can allocate almost all the system memory to Java by starting the tool from the command linewith something like `java -Xmx12288M -jar NMONVisualizer.jar`. That would use 12GB of memory but you may need more. You probably want to try 50 or so files first and see how much memory is being used to get an idea if this will work. You can see memory usage in the tool by looking at the Total Heap Usage value in Help -> Java Info.

If that's still not enough, I think the only other solution is to parse out just the data you need from the NMON files and try and process those (still with a high -Xmx setting). The minimal data for CPU is the `AAA`, `ZZZ` and `CPU_ALL` records. From a bash command line, you could do something like:

    for f in `ls -1 *nmon`; do grep "AAA\|CPU_ALL\|ZZZ" $f > ${f}_reduced;done

to create a new set of 'reduced' nmon files and try and process those.
