### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by tiwarishiv** [nmonvisualizer/nmonvisualizer#52]
/Users/shivtiwari/Documents/skt/ISL/customer/ShopperStop/Apr18/os_output/ofdb-nmon/ofdb_180413_0800.nmon:
WARNING  not creating ERROR data type at line 28 for data [ERROR, T0000, errno=46 pathconf failed for /dev/cd0.]
WARNING  command line for process id 24904046 redefined at line 80365
WARNING  command line for process id 57868746 redefined at line 81463
WARNING  command line for process id 45351410 redefined at line 85801

**Comment by hpresnall** [comment]
These are all warnings and the file should have been processed ok otherwise.
The first one indicates that NMON wrote an ERROR to the file - looks like it couldn't get info about the cd drive.
The others indicate that there were multiple `UARG` lines for the same process id. The second one for each process id was the same so you get a warning to alert you. But, I don't know why NMON would output this. Note there will be a different warning of the pid is reused because the command line would be different. If you want to verify things are ok, grep the nmon file for `UARG` and the processid.
