### ISSUE TITLE
How to set shape of data points on a linechart or disable the data points

### ISSUE THREAD

**Issue by scbray1** [nmonvisualizer/nmonvisualizer#63]
I would like to make a custom linechart showing just the lines without any data points on the lines. Does Nmon Visualizer have a way of disabling, making invisible or changing the shape of the data points ? I see that JFreeChart has setBaseShape and setSeriesShape methods that could do it.

**Comment by scbray1** [comment]
I see that https://nmonvisualizer.github.io/nmonvisualizer/customreports.html mentions a showMarkers attribute for histogram charts. Could that be applied to linecharts ?

**Comment by hpresnall** [comment]
Added a `showDataPoints` attribute to `<linechart>` and `<intervalchart>` which can be set to `false` to remove the data points from all the lines on the chart.

Is that enough? Setting custom shapes would be more difficult since it would require defining a number of basic shapes with known names. Custom shapes would be even harder if you wanted to specify custom polygons.

**Comment by scbray1** [comment]
That would be enough for me. Changing the shape would be a nice-to-have feature.
