### ISSUE TITLE
Nmon Visualizer WARNING  command line for process id 48759000 redefined at line 377565

### ISSUE THREAD

**Issue by scbray1** [nmonvisualizer/nmonvisualizer#65]
I am using NMONVisualizer_2019-01-06.jar and I get a strange error when analysing my nmon files:

$ cat ReportGenerator_20190222_040016.log
/testdata/nmon/logs/20190221/20190221_0000_05h.nmon:
WARNING  command line for process id 48759000 redefined at line 377565

What does it mean and could the message be reworded to be more helpful and to give the name of the source file ?

**Comment by hpresnall** [comment]
Is `/testdata/nmon/logs/20190221/20190221_0000_05h.nmon` not the correct file name?

That's a warning messsage to indicate that a process id was reused. Parsing of the NMON file should not be effect and all the rest of the data is there. I am guessing that happened because this nmon file spanned a long time frame and the system was creating a lot of processes.

But, looking at the [code](https://github.com/nmonvisualizer/nmonvisualizer/blob/828e0ab25ee463433ccf10fdbf3d8e76da2a942d/src/com/ibm/nmon/parser/NMONParser.java#L732) again, the message does need to be changed since the command line _was not_ change, in fact. The process id was reused, but so was the name _and_ it has the same command line arguments in the `UARG` line. I've only seen this happen once before: see #52 .

This is probably not going to happen very often. In effect you have a new process, but it looks the same so the program keeps the same process info and adds new data to it. I assume the chart for that process would have a gap in the data for some period of time.

**Comment by scbray1** [comment]
Thanks. The error message makes sense now.

I removed the hostname from the nmon file name for .security reasons.
The nmon file spanned 5 hours and there were about 700 processes active at any time.
