### ISSUE TITLE
Create XML from GUI?

### ISSUE THREAD

**Issue by LD-Auto** [nmonvisualizer/nmonvisualizer#77]
Hello,

I'm writing to request a feature that could help creating reports in an automated way:
Creating XML files from the GUI.
The CMD line feature is incredibly useful but creating the right XML file to get custom reports is not so intuitive (not that it should be but... it would help)
So the idea is a way to open a *.nmon from the SW, select the desired values to report and then select a "generate XML" function. 
It could then be fed to the command line utility to get custom reports

**Comment by hpresnall** [comment]
This would be a pretty large new feature. The issue is that I think the complexity of the XML file would require a point and click GUI element to match all the attributes. Certainly possible, but not simple.

How complex are your reports and how often are you changing them?
If you are just needing help on creating something, see what[ the tool itself uses](https://github.com/nmonvisualizer/nmonvisualizer/tree/master/src/com/ibm/nmon/report) for examples. From the GUI, you can also open the Custom Report UI (View -> Custom Report). From this window, you can load an xml file. This should allow easier iterative development since you can make changes, reload and see the charts immediately.

**Comment by LD-Auto** [comment]
That's plenty of info to work on,thank you
