### ISSUE TITLE
JVM GC output cannot be parsed when the JVM GC policy is set to 'Balanced'

### ISSUE THREAD

**Issue by NiallWard** [nmonvisualizer/nmonvisualizer#88]
When parsing a file either through code or with the NMONVisualizer client , you get the following when trying to process a GC log file generated by a JVM with the GC policy set to 'Balanced':

ava.lang.IllegalArgumentException: record does not contain any data for DataType GCBEF (gc)
	at com.ibm.nmon.data.DataRecord.getData(DataRecord.java:95)
	at com.ibm.nmon.parser.gc.state.JavaGCCycle.calculateTotalSizes(JavaGCCycle.java:45)
	at com.ibm.nmon.parser.gc.state.Java7GCCycle.endElement(Java7GCCycle.java:110)
	at com.ibm.nmon.parser.gc.VerboseGCParser.endElement(VerboseGCParser.java:85)
	at com.ibm.nmon.parser.BasicXMLParser.parse(BasicXMLParser.java:148)
	at com.ibm.nmon.parser.BasicXMLParser.parse(BasicXMLParser.java:27)
	at com.ibm.nmon.parser.gc.VerboseGCParser.parse(VerboseGCParser.java:52)
	at com.ibm.nmon.NMONVisualizerApp.parse(NMONVisualizerApp.java:163)
	at com.ibm.nmon.gui.file.ParserRunner.run(ParserRunner.java:73)
	at java.lang.Thread.run(Unknown Source)

**Comment by hpresnall** [comment]
The GC parser code is pretty old, so I am not surprised newer GC policies don't work.

If you want to attach a sample log, I can take a look and see how much effort it would be to add. I am not 100% sure balanced GC data would even fit into the current data model / data types that currently exist.

**Comment by NiallWard** [comment]
Hi 

Apologies, I missed the update during IBM's mail difficulties. Please find attached an example verbose gc file

[verbosegc.log](https://github.com/nmonvisualizer/nmonvisualizer/files/6822570/verbosegc.log)

**Comment by hpresnall** [comment]
I've added code that _skips_ processing of data when this happens. However, the root cause is that the data the parser expects at the beginning of the GC cycle is not present for one or more of the collections. So, at the end of the GC cycle, data _will not_ be calculated. See [com.ibm.nmon.parser.gc.state.JavaGCCycle.calculateTotalSizes(GCParserContext)](https://github.com/nmonvisualizer/nmonvisualizer/commit/d3ade5542da9fb901dba916eaf63d75c9cbd6cb0#diff-8d8a6973f9f0eeb4439b54315891c88c734a8c6112d46dae98d8aef55d85ec41L41).

I'd need to study a lot more of what balanced GC in this JVM version is actually doing to understand the effect of this. To really fix it, new calculations and maybe even completely new handling of the data is needed. At this point, I think it might be better for you look at other GC parsers that focus on keeping up with all the different GC methods.

**Comment by NiallWard** [comment]
ok, thanks for the investigation and endeavoring to fix the issue
