### ISSUE TITLE
How to save charts to PNG files in GUI ?

### ISSUE THREAD

**Issue by scbray1** [nmonvisualizer/nmonvisualizer#92]
https://nmonvisualizer.github.io/nmonvisualizer/index.html  
says that Nmon Visualizer GUI can save charts to PNG files
but doesn't explain how to do it.

Is there a Save All Charts feature ?

**Comment by hpresnall** [comment]
In the gui, you can also right click on the tree. Right ckicking on the top level and selecting Save Charts will create charts for all the summary tabs. Clicking on a dataset/host will create all the charts for that host.

The default command line is equivalent to doing this for the top level and all the hosts.

**Comment by scbray1** [comment]
When you use Save Charts it doesn't save them in the current directory (from which Nmon Visualizer loaded the nmon file). Instead the GUI offers the Windows default directory, which means you have to traverse the directory tree every time.

**Comment by hpresnall** [comment]
All save dialogs use the Java Preferences API to [store the last directory ](https://github.com/nmonvisualizer/nmonvisualizer/blob/master/src/com/ibm/nmon/gui/file/GUIFileChooser.java#L79) you used. This should persist across app restarts since Preferences are stored in the operating system.

If it's not working, something in the OS (or Java security manager) is probably not letting you save preferences. Another way to tell is change the window size and position of the application. This is also saved, so if NMONVisualizer doesn't start in the same position as the last time you closed it, we know the underlying issue.

What OS are you on?

**Comment by scbray1** [comment]
I'm using Microsoft Windows 10 Enterprise and Java 8 to view the nmon files in the GUI.

**Comment by hpresnall** [comment]
Do you see any output if you run the jar file from a command line? I'd expect something like `Could not open/create prefs root node ...`.

In the meantime, I've updated the code so it at least defaults to the current working dir.
